Write a e PHP script to display string, values within a table.

<br/>

<?php
$sal1 = 1000;
$sal2 = 2000;
$sal3 = 1650;

echo "<table border=1 cellspacing=0 cellspacing=0>

<tr> <td><font color=blue>Salariul pentru Alex este</td> <td>$sal1$</font></td></tr>
<tr> <td><font color=blue>Salariul pentru Ion este</td> <td>$sal2$</font></td></tr>
<tr> <td><font color=blue>Salariul pentru Maria este</td> <td>$sal3$</font></td></tr>

";

?>