
Write a PHP script, which will return the following components of the url 'https://www.w3resource.com/php-exercises/php-basic-exercises.php'.<br />
List of components : Scheme, Host, Path <br >


<?php

$url = 'https://www.w3resource.com/php-exercises/php-basic-exercises.php';

$scheme = parse_url($url, PHP_URL_SCHEME);
$host = parse_url($url, PHP_URL_HOST);
$path = parse_url($url, PHP_URL_PATH);
?>
Scheme: <?php echo $scheme ?> <br/>
Host:  <?php echo $host ?>  <br/>
Path: <?php echo $path ?> <br/>

