<?php $number = array(5, 10, 15, 20, 25, 30); ?> <br/>
<?php echo $number[3]; ?> <br/>


<?php $mix = array(1, "fox", "chicken", 12, array("x", "y", "z")); ?>
<?php echo $mix[2]; ?><br/>
<?php //echo $mix[1]; ?><!--<br/>-->
<?php //echo $mix; ?><!--<br/>-->

<?php echo $mix[3][1]; ?> <br/>

<?php $mix[2] = "cat"; ?>
<?php $mix[4] = "mouse"; ?>
<?php $mix[1] = "cal"; ?>


    <pre>
    <?php echo print_r($mix); ?>
</pre>

<?php

$array = [1, 2, 3, 4, 5];
echo $array[1];
?>