<?php

$variabila1 = 4;
$variabila2 = 16;

?>

    Basic Math: <?php echo ((1 + 2 + $variabila1) * $variabila2) / 2 - 4; ?> <br/>

    <br/>
    Absolute value: <?php echo abs(0 - 500); ?> <br/>
    Exponential : <?php echo pow(2, 10); ?> <br/>
    Square root: <?php echo sqrt(200); ?> <br/>
    Modulo: <?php echo fmod(31, 5); ?> <br/>
    Random : <?php echo rand(); ?> <br/>
    Random (min, max): <?php echo rand(1, 5); ?> <br/>

    <br/>
    += : <?php $variabila1 += 4;
echo $variabila1; ?> <br/>

    -= : <?php $variabila1 -= 4;
echo $variabila1; ?> <br/>

    *= : <?php $variabila1 *= 3;
echo $variabila1; ?> <br/>

    /= : <?php $variabila1 /= 4;
echo $variabila1; ?> <br/>

    <br/>
    Increment: <?php $variabila1++;

echo $variabila1; ?> <br/>

    Decrement: <?php $variabila1--;
echo $variabila1; ?> <br/>

    <br/>
<?php

echo "9 copac" + "4 copaci";

?>