<?php echo $float = 3.15; ?> <br/>
<?php echo $float + 2; ?> <br/>
<?php echo 4 / 1; ?> <br/>

<br/>
Round: <?php echo round($float, 1); ?> <br/>
Ceiling: <?php echo ceil($float); ?> <br/>
Floor: <?php echo floor($float); ?> <br/>

<!--Ceil round fraction up;-->
<!--Floor rond fraction down;-->

<br/>

<?php $integer = 2; ?>

<?php echo "Is {$integer} integer? " . is_int($integer); ?> <br/>
<?php echo "Is {$float} integer? " . is_int($float); ?> <br/>

<br/>
<?php echo "Is {$integer} float? " . is_float($integer); ?> <br/>
<?php echo "Is {$float} float? " . is_float($float); ?> <br/>

<br/>
<?php echo "Is {$integer} numeric? " . is_numeric($integer); ?> <br/>
<?php echo "Is {$float} numeric? " . is_numeric($float); ?> <br/>