<?php

$prima = "Hello my friends!";
$aDoua = "Out of memory.";

$aTreia = $prima;
$aTreia .= $aDoua;
echo $aTreia;


?>
<br/>


Lowercase: <?php echo strtolower($aTreia); ?><br/>
Uppercase: <?php echo strtoupper($aTreia); ?><br/>
Uppercase first: <?php echo ucfirst($aTreia); ?><br/>
Uppercase words: <?php echo ucwords($aTreia); ?><br/>

<br/>
Length: <?php echo strlen($aTreia); ?> <br/>
Trim: <?php echo "A" . trim("B C D ") . "E"; ?> <br/>
Find: <?php echo strstr($aTreia, "of"); ?> <br/>
Replace by string: <?php echo str_replace("Hello", "Good Bye", $aTreia); ?><br/>

<br/>
Repeat: <?php echo str_repeat($aTreia, 2); ?> <br/>
Make substring: <?php echo substr($aTreia, 4, 10); ?> <br/>
Find position: <?php echo strpos($aTreia, "memory"); ?> <br/>
Find charcter: <?php echo strchr($aTreia, "o"); ?> <br/>
